"use client"

import { useEffect, useState } from "react"
import { AnimatePresence, motion, useReducedMotion } from "framer-motion"
import { ArrowDownRight, ArrowRight, ArrowUpRight, Check, ChevronDown, Menu, Play, X } from "lucide-react"

const navItems = ["Work", "Services", "About", "Contact"]
const services = [
  ["01", "Social media marketing", "Strategic content and campaigns that build awareness, engagement and community."],
  ["02", "Paid advertising", "Campaigns designed to reach the right audiences and generate measurable results."],
  ["03", "SEO", "Search visibility that brings the people actively looking for what you do."],
  ["04", "Content creation", "Visual and written content that captures attention and communicates clearly."],
  ["05", "Video production", "Engaging films for social, campaigns, promotions and digital platforms."],
  ["06", "Branding", "Visual identities that make businesses recognizable, consistent and memorable."],
  ["07", "Web design & development", "Modern digital experiences shaped around your brand and business goals."],
  ["08", "Marketing strategy", "Research, positioning and planning built around real business goals."],
  ["09", "Copywriting", "Clear, persuasive messaging for ads, social, websites and campaigns."],
]
const toolkit = [
  ["ADVERTISING", "Facebook Ads", "Campaign architecture and paid reach."], ["ADVERTISING", "Google Ads", "Intent-led acquisition."], ["ADVERTISING", "Meta Business Suite", "Audience and content operations."],
  ["ANALYTICS & SEARCH", "SEO", "Search visibility and discovery."], ["ANALYTICS & SEARCH", "Google Analytics", "Signals behind the story."],
  ["DESIGN", "Photoshop", "Image-making and campaign craft."], ["DESIGN", "Illustrator", "Identity systems and vectors."], ["DESIGN", "Canva", "Fast, flexible content systems."],
  ["VIDEO", "Premiere Pro", "Editing with rhythm and intention."], ["VIDEO", "CapCut", "Short-form content in motion."], ["VIDEO", "Video editing", "The cut is where meaning moves."],
  ["STRATEGY & CREATIVE", "Copywriting", "Words that make ideas land."], ["STRATEGY & CREATIVE", "Marketing strategy", "A direction for every decision."], ["STRATEGY & CREATIVE", "Branding", "Making the invisible recognizable."],
]
const projects = [
  { number: "01", name: "[CLIENT NAME]", category: "Industry / Category", description: "A place for campaign evidence, creative direction and the story behind the work.", services: ["Social media", "Content creation", "Branding"], className: "project-readeth" },
  { number: "02", name: "[CLIENT NAME]", category: "Industry / Category", description: "Add a case study narrative here: the challenge, the shift and the work that followed.", services: ["Paid advertising", "Web design", "Strategy"], className: "project-ethbuy" },
]
const videos = [
  ["[VIDEO TITLE]", "Social media", "Add a video description and an editable YouTube, Vimeo or MP4 URL."] ,
  ["[VIDEO TITLE]", "Promotional video", "A second motion story can live here when the source is ready."],
  ["[VIDEO TITLE]", "Short-form content", "A home for reels, edits and campaign moments."],
]
const team = [["[TEAM MEMBER NAME]", "[ROLE]", "[DESCRIPTION]"], ["[TEAM MEMBER NAME]", "[ROLE]", "[DESCRIPTION]"], ["[TEAM MEMBER NAME]", "[ROLE]", "[DESCRIPTION]"]]
const reveal = { hidden: { opacity: 0, y: 32 }, visible: { opacity: 1, y: 0 } }
const ease = { duration: .8, ease: [0.22, 1, 0.36, 1] as const }

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) { return <motion.div className={className} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .15 }} variants={reveal} transition={{ ...ease, delay }}>{children}</motion.div> }
function Logo({ light = false }: { light?: boolean }) { return <a href="#home" className={`flex items-center gap-3 font-semibold tracking-[-0.04em] ${light ? "text-background" : "text-foreground"}`}><span className="logo-mark">g</span><span className="text-[1.1rem]">girum<span className="text-primary">.</span></span></a> }
function ButtonLink({ children = "Start a project", inverse = false }: { children?: React.ReactNode; inverse?: boolean }) { return <a href="#contact" className={`group inline-flex items-center gap-4 border px-5 py-3 text-[0.7rem] font-semibold uppercase tracking-[.18em] transition duration-500 ${inverse ? "border-background/20 bg-background text-background hover:bg-primary" : "border-foreground/20 hover:border-primary hover:text-primary"}`}><span>{children}</span><ArrowUpRight className="size-4 transition group-hover:-translate-y-1 group-hover:translate-x-1" /></a> }
function SectionHead({ index, aside }: { index: string; aside?: React.ReactNode }) { return <div className="section-top"><span className="section-index">{index}</span>{aside && <span className="section-aside">{aside}</span>}</div> }
function Hero({ reduced }: { reduced: boolean }) { return <section id="home" className="hero-section"><div className="hero-grid" /><div className="hero-glow" /><div className="hero-content page-shell"><motion.p className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ ...ease, delay: .5 }}><span /> Creative digital agency</motion.p><motion.h1 initial={{ opacity: 0, y: 50 }} animate={{ opacity: 1, y: 0 }} transition={{ ...ease, delay: .65 }}>We turn<br /><em>attention</em><br />into growth<span className="text-primary">.</span></motion.h1><motion.div className="hero-bottom" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ ...ease, delay: 1 }}><p>Strategy, creative and digital experiences built to make ambitious brands impossible to ignore.</p><ButtonLink /></motion.div></div><motion.div className="hero-art" animate={reduced ? undefined : { y: [0, -12, 0] }} transition={{ duration: 7, repeat: Infinity, ease: "easeInOut" }} aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-sphere" /><div className="browser-frame browser-back"><div className="browser-bar"><span /><span /><span /><i>girum / studio</i></div><div className="mockup-dark"><span>01 / digital culture</span><strong>Make<br />meaning<br />move.</strong><div className="mockup-line" /></div></div><div className="browser-frame browser-front"><div className="browser-bar"><span /><span /><span /><i>girum / 2026</i></div><div className="mockup-light"><span>ReadEth — 2026</span><strong>Read<br /><i>between</i><br />the lines.</strong><div className="mockup-circle" /></div></div></motion.div><div className="hero-scroll page-shell">Scroll to explore <ArrowDownRight className="size-4" /></div></section> }
function Marquee() { return <section className="marquee-section"><div className="page-shell marquee-label">Built for ambitious brands</div><div className="marquee-track">{[...Array(2)].flatMap(() => ["Branding", "Social media", "Content", "Digital campaigns", "Web design", "Performance"]).map((item, i) => <span key={`${item}-${i}`}>{item}<b>✳</b></span>)}</div></section> }
function About() { return <section id="about" className="about-section page-shell"><Reveal><SectionHead index="02 — About Girum" aside={<>Strategy × creativity<br />Addis Ababa / Everywhere</>} /></Reveal><Reveal><h2>We don&apos;t just<br />market brands.<br /><i>We make them matter.</i></h2></Reveal><div className="about-bottom"><Reveal><p className="large-copy">Girum Marketing & Promotion is a creative digital marketing agency focused on helping businesses build stronger brands, connect with the right audiences and turn attention into meaningful growth.</p><p className="muted-copy">We combine strategy, creativity, content, technology, digital marketing and data to create campaigns and digital experiences that help businesses grow.</p></Reveal><Reveal className="board-art" delay={.12}><div className="board-grid" /><div className="board-card board-card-a">campaign<br /><i>in motion</i></div><div className="board-card board-card-b">[ SOCIAL<br />POST ]</div><div className="board-stat">clarity<br /><span>×</span> craft<br /><span>×</span> growth</div></Reveal></div></section> }
function Drivers() { const [active, setActive] = useState(0); const items = [["MISSION", "To help businesses communicate better, connect with their audiences and grow through creative, strategic and effective digital marketing."], ["VISION", "To become a trusted creative growth partner for ambitious businesses in Ethiopia and beyond."], ["VALUES", "Creativity, results, integrity, collaboration and continuous learning — the standards behind the work."]]; return <section className="drivers-section"><div className="page-shell"><Reveal><SectionHead index="03 — What drives us" /></Reveal><Reveal><h2 className="section-heading">Built with<br /><i>purpose.</i></h2></Reveal><div className="driver-list">{items.map(([title, text], i) => <button key={title} className={`driver-row ${active === i ? "is-active" : ""}`} onClick={() => setActive(i)}><span className="driver-number">0{i + 1}</span><strong>{title}</strong><p>{active === i ? text : ""}</p><ChevronDown className="driver-chevron" /></button>)}</div><div className="values-line">{["CREATIVITY", "RESULTS", "INTEGRITY", "COLLABORATION", "CONTINUOUS LEARNING"].map(value => <span key={value}><Check />{value}</span>)}</div></div></section> }
function Services() { const [active, setActive] = useState(0); return <section id="services" className="services-section"><div className="page-shell"><Reveal><SectionHead index="04 — What we do" aside="Strategy, creativity and digital execution designed to help brands get noticed and grow." /></Reveal><Reveal><h2 className="section-heading">The work behind<br /><i>the wow.</i></h2></Reveal><div className="service-list">{services.map(([num, title, text], i) => <button key={num} className={`service-row ${active === i ? "is-active" : ""}`} onMouseEnter={() => setActive(i)} onFocus={() => setActive(i)} onClick={() => setActive(i)}><span className="service-number">{num}</span><span className="service-title">{title}</span><span className="service-copy">{text}</span><ArrowUpRight className="service-arrow" /></button>)}</div><div className={`service-preview screen-${active}`}><div><span className="preview-label">Currently exploring / {services[active][0]}</span><strong>{services[active][1]}</strong><p>{services[active][2]}</p></div><div className="preview-collage"><span>REELS</span><span>DATA</span><span>BRAND</span><span>WORDS</span></div></div></div></section> }
function Toolkit() { return <section className="toolkit-section"><div className="page-shell"><Reveal><SectionHead index="05 — Our toolkit" aside="The tools, platforms and skills behind the work." /></Reveal><Reveal><h2 className="section-heading">A wall of<br /><i>possibility.</i></h2></Reveal><div className="toolkit-wall">{toolkit.map(([category, name, description]) => <div className="tool-item" key={name}><span className="tool-icon">✳</span><span className="tool-category">{category}</span><strong>{name}</strong><p>{description}</p></div>)}</div></div></section> }
function Projects({ onOpen }: { onOpen: (name: string) => void }) { return <section id="work" className="work-section page-shell"><Reveal><SectionHead index="06 — Brands we&apos;ve helped grow" aside="Real projects. Real work. Real stories." /></Reveal><Reveal><h2 className="section-heading">Evidence<br /><i>over promises.</i></h2></Reveal><div className="project-stack">{projects.map((project, index) => <Reveal key={project.number}><button className="project-case" onClick={() => onOpen(project.name)}><div className={`project-visual ${project.className}`}><div className="project-noise" /><span className="project-tag">{project.number} / [PROJECT IMAGE]</span><div className="project-ui"><small>{project.name} / {project.category}</small><strong>{index ? <>Your story<br /><i>goes here.</i></> : <>Show the<br /><i>evidence.</i></>}</strong><div className="project-ui-line" /></div></div><div className="project-caption"><div><span>{project.category}</span><h3>{project.name}</h3></div><ArrowUpRight /></div></button></Reveal>)}</div></section> }
function VideoShowcase({ onOpen }: { onOpen: (name: string) => void }) { return <section className="video-section"><div className="page-shell"><Reveal><SectionHead index="07 — Watch the work" aside="See our ideas in motion." /></Reveal><Reveal><h2 className="section-heading">Ideas in<br /><i>motion.</i></h2></Reveal><div className="video-feature" onClick={() => onOpen(videos[0][0])}><div className="video-placeholder"><span>[ VIDEO THUMBNAIL ]</span><button aria-label="Play video"><Play fill="currentColor" /></button></div><h3>{videos[0][0]}</h3><p>{videos[0][1]} / {videos[0][2]}</p></div><div className="video-row">{videos.slice(1).map((video, index) => <button key={`${video[0]}-${index}`} onClick={() => onOpen(video[0])}><div className="video-small"><Play fill="currentColor" /></div><span>{video[1]}</span><strong>{video[0]}</strong></button>)}</div></div></section> }
function Team() { return <section className="team-section page-shell"><Reveal><SectionHead index="08 — The people behind the work" aside="The people turning strategy into creative work." /></Reveal><Reveal><h2 className="section-heading">Small team.<br /><i>Big energy.</i></h2></Reveal><div className="team-grid">{team.map(([name, role, description], i) => <article className="team-member" key={`${name}-${i}`}><div className="team-image"><span>[ TEAM MEMBER IMAGE ]</span></div><div className="team-meta"><div><h3>{name}</h3><p>{role}</p></div><ArrowUpRight /></div><span className="team-description">{description}</span><div className="social-links"><a href="#contact">LinkedIn</a><a href="#contact">Instagram</a></div></article>)}</div></section> }
function Contact() { return <section id="contact" className="contact-section"><div className="contact-grid" /><div className="page-shell contact-inner"><Reveal><SectionHead index="09 — Let&apos;s talk" /><h2>Let&apos;s build<br /><i>something great.</i></h2><p>Have a project, campaign or idea in mind? Let&apos;s talk.</p></Reveal><form className="contact-form" onSubmit={e => e.preventDefault()}><div className="form-row"><label>Name<input placeholder="Your name" required /></label><label>Email<input type="email" placeholder="you@company.com" required /></label></div><div className="form-row"><label>Phone<input placeholder="+251 ..." /></label><label>Company<input placeholder="Company name" /></label></div><label>Service needed<select defaultValue=""><option value="" disabled>Select a service</option>{services.map(([, title]) => <option key={title}>{title}</option>)}<option>Other</option></select></label><label>Message<textarea placeholder="Tell us about your project..." rows={5} /></label><button className="submit-button" type="submit">Send inquiry <ArrowUpRight /></button></form><div className="contact-details"><div><span>EMAIL</span><strong>[EMAIL ADDRESS]</strong></div><div><span>PHONE</span><strong>[PHONE NUMBER]</strong></div><div><span>LOCATION</span><strong>Ethiopia</strong></div><div><span>SOCIAL</span><strong>Instagram / Facebook / LinkedIn / TikTok</strong></div></div></div></section> }
function Footer() { return <footer className="footer-section page-shell"><div className="footer-top"><Logo /><span>Marketing & Promotion</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Girum Marketing & Promotion</span><span>Addis Ababa / Worldwide</span></div></footer> }
function Lightbox({ title, onClose }: { title: string | null; onClose: () => void }) { return <AnimatePresence>{title && <motion.div className="lightbox" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><button className="lightbox-close" onClick={onClose} aria-label="Close preview"><X /></button><div className="lightbox-content"><span>[ EDITABLE MEDIA AREA ]</span><h2>{title}</h2><p>Add a real image, gallery, video URL or campaign evidence here.</p></div></motion.div>}</AnimatePresence> }
export default function Page() { const reduced = useReducedMotion(); const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const [lightbox, setLightbox] = useState<string | null>(null); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll) }, []); useEffect(() => { document.body.style.overflow = menuOpen || !!lightbox ? "hidden" : ""; return () => { document.body.style.overflow = "" } }, [menuOpen, lightbox]); return <><header className={`site-nav ${scrolled ? "is-scrolled" : ""}`}><Logo /><nav>{navItems.map(item => <a href={`#${item.toLowerCase()}`} key={item}>{item}</a>)}<ButtonLink /></nav><button className="menu-button" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></header><AnimatePresence>{menuOpen && <motion.div className="mobile-menu" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><Logo light /><div className="mobile-links">{navItems.map((item, i) => <motion.a initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * .07 }} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)} key={item}>{item}<ArrowUpRight /></motion.a>)}</div><span className="mobile-note">Girum Marketing & Promotion<br />Addis Ababa / Everywhere</span></motion.div>}</AnimatePresence><main><Hero reduced={!!reduced} /><Marquee /><About /><Drivers /><Services /><Toolkit /><Projects onOpen={setLightbox} /><VideoShowcase onOpen={setLightbox} /><Team /><Contact /></main><Footer /><Lightbox title={lightbox} onClose={() => setLightbox(null)} /></> }
